/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Laurie' at '08/01/16 14:11' with Gradle 2.9
 *
 * @author Laurie, @date 08/01/16 14:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
